# Generated by Django 3.0.4 on 2020-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('about', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
