# Generated by Django 3.0.4 on 2020-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=80, null=True)),
                ('p_image', models.ImageField(upload_to='profile/')),
                ('p_description', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
