# Generated by Django 3.0.4 on 2020-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('g_id', models.IntegerField(primary_key=True, serialize=False)),
                ('g_image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
