# Generated by Django 3.0.4 on 2020-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0005_tolls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=50)),
                ('skill_sub_title', models.CharField(max_length=80)),
            ],
        ),
    ]
