# Generated by Django 3.0.4 on 2020-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0007_auto_20200325_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSkill',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
